class TestData:

    eicher_price =  1266
    eicher_count = 10
    itc_price = 171.02
    itc_count = 600
    reliance_price = 981.87
    reliance_count = 50
    tatamotors_price = 66.08
    tatamotors_count = 200
    vodafone_price = 3.15
    vodafone_count = 1000
    equitas_price = 122
    equitas_count = 811
    federalbank_price = 56.30
    federalbank_count = 302
    indoco_count = 220
    indoco_price = 449
    irb_price = 127.5
    irb_count = 199
    kopran_price = 204
    kopran_count = 245
    neuland_price = 1999
    neuland_count = 50
    praj_price = 297.24
    praj_count = 333

    eicher_search = "Eicher Motors Share"
    itc_search = "ITC Share"
    reliance_search = "Reliance Share"
    tatamotors_search = "Tata Motors Share"
    vodafone_search = "vodafone idea share"
    equitas_search = "Equitas Holdings Share"
    federalbank_search = "Federal Bank Share"
    indoco_search = "Indoco Remedies Share"
    irb_search = "IRB Share"
    kopran_search = "Kopran Share"
    neuland_search = "Neuland Share"
    praj_search = "Praj Industries Share"
